stopping_power_source_name: "PSTAR"
stopping_power_source_no:  2  # PSTAR


# LET_normalised means if the radial dose integral should yield the LET
Cucinotta:
  RDD_model: "RDD_CucinottaPoint"
  ER_model: "ER_Tabata"
  LET_normalised: false
  a0_nm: 10
  r_min_m: !!float 5e-11
  d_min_Gy: !!float 1e-8

CucinottaExtTarget:
  RDD_model: "RDD_CucinottaExtTarget"
  ER_model: "ER_Tabata"
  LET_normalised: true
  a0_nm: 10
  r_min_m: !!float 5e-11
  d_min_Gy: !!float 1e-8

Geiss:
  RDD_model: "RDD_Geiss"
  ER_model: "ER_Geiss"
  LET_normalised: false
  a0_nm: 10
  r_min_m: !!float 5e-11
  d_min_Gy: !!float 1e-8
